### ISSUE TITLE
Ch08-Dockerfile with a dependency

### ISSUE THREAD

**Issue by eliassal** [sixeyed/diamol#12]
Elton, when you try to run a container using
docker container run -d -p 8082:80 diamol/ch08-numbers-web
you show that the container exists right away ahen you list containers --all

This is not the case on my machine. I also deleted the container and image, then I build locally the imsgae using the dickerfile at
ch08/exercises/numbers/numbers-web/Dockerfile.v2
it gave the same thing, container does not exist and I can browse the application docker ps
![containerDepend](https://user-images.githubusercontent.com/8447864/84525947-c5d3dc00-acdc-11ea-8111-1d360c399df9.jpg)

**Comment by sixeyed** [comment]
Hi @eliassal - sorry for not getting back to you. I think 'immediately' is the issue here :) I've just run the exercise again and it takes just a few seconds longer for the startup check to exit the container:

```
PS>docker ps -a
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS                        PORTS     NAMES
0df1efdd9f7a   diamol/ch08-numbers-web:v2   "/bin/sh -c 'curl --…"   18 seconds ago   Exited (6) 13 seconds ago               vigilant_stonebraker
```
