### ISSUE TITLE
curious content in readme for first exercise, chapter 2 

### ISSUE THREAD

**Issue by carehart** [sixeyed/diamol#15]
Elton, can you look over the readme for the first exercise of chapter 2 (indeed the first exercise in the book), at  ch02/exercises/hello-diamol/README.md? It makes reference to things that are not at all a part of chapter 2, from enabling experimental features in the docker config, to enabling multi-arch support, to working with manifests, docker inspect, and docker push.

It really seems that this is stuff that might come up in Ch 16 instead (though as I look at the files for that, I see none referring to the same commands, Maybe this ch02/exercises/hello-diamol/README.md reflects a variation from an early revision of the book?

**Comment by sixeyed** [comment]
Thanks Charlie - yes, it was some old notes which I didn't clean up, but they're gone now :)
