### ISSUE TITLE
Chapter 14 lab - healthcheck

### ISSUE THREAD

**Issue by oleg-glushko** [sixeyed/diamol#16]
Both ch04-image-of-the-day and ch09-image-of-the-day images don't include a curl application, so you can't write a healthcheck test using it. Both images don't include a curl application, so you can't write a healthcheck test using it. One either has to update these images or use a stub check like the "true" bash command to proceed.

![image](https://user-images.githubusercontent.com/44775781/89724880-01c0be80-da4c-11ea-8e47-17025c373ad6.png)

**Comment by xtbe** [comment]
Fixing the image would probably my preferred approach but I took the opportunity to learn overriding the ENTRYPOINT in the docker-compose file and install curl, not recommended but it works

 ```
...
 iotd:
    image: diamol/ch04-image-of-the-day
    entrypoint: ["sh", "-c", "apt-get update ; apt-get install -y curl; java -jar /app/iotd-service-0.1.0.jar"]
...
```

**Comment by sixeyed** [comment]
Thanks for sending the issue Tom - nice hack too :) I've updated the Dockerfiles and pushed new versions of the ch04 images, so this should be fixed now.
