### ISSUE TITLE
Page 24 command exits with error

### ISSUE THREAD

**Issue by BansheePrime** [sixeyed/diamol#24]
**Exercise**
Page 24
docker container run --detach --publish 8088:80 diamol/ch02-hellodiamol-web

**Problem**
Unable to find image 'diamol/ch02-hellodiamol-web:latest' locally
docker: Error response from daemon: pull access denied for diamol/ch02-hellodiamol-web, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Docker version**
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:31 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Code version**
commit 19a8d04b1b4df0392ae6091c6ead8a680ad72368 (HEAD -> master, origin/master, origin/HEAD)
Author: Elton Stoneman <elton@sixeyed.com>
Date:   Fri Sep 25 09:10:55 2020 +0100

    Add ep. 20

**Additional context**

**Comment by BansheePrime** [comment]
Solved
command copy/paste drops dash in ch02-hello-diamol-web

**Comment by androchentw** [comment]
The Chinese version of this book is having the same issue in demo code on page 2-16.

❌ `docker container run --detach --publish 8088:80 diamol/ch02-hellodiamol-web`
✅ `docker container run --detach --publish 8088:80 diamol/ch02-hello-diamol-web`

中文版的書在 2-16 頁的 "馬上試試" 也有類似狀況 (譯名 《跟著 Docker 隊長，修練 22天就精通 - 搭配 20小時作者線上教學，無縫接軌 Microservices、Cloud-native、Serverless、DevOps 開發架構》)
提供給需要的人參考.

**Comment by lcslin** [comment]
same from a Chinese reader. check the continer name as following:
```
docker container run --detach --publish 8088:80 diamol/ch02-hello-diamol-web
Unable to find image 'diamol/ch02-hello-diamol-web:latest' locally
latest: Pulling from diamol/ch02-hello-diamol-web
f84cab65f19f: Pull complete 
87259b7246e5: Pull complete 
3e84dc11ea39: Pull complete 
d632c8441234: Pull complete 
0fcb24848396: Pull complete 
af7e90cfff46: Pull complete 
Digest: sha256:fe5a4c954fe2df5cadeea304ab632533f8ece9e31bd219ea22fdbf8b597571eb
Status: Downloaded newer image for diamol/ch02-hello-diamol-web:latest
a1d55905e0db85d1357813c3910d91102c55429f4a4e7397f126ef3828b4ce24
```
