### ISSUE TITLE
CH15 Jenkins does not have diamol job

### ISSUE THREAD

**Issue by IraIAmOnIt** [sixeyed/diamol#26]
**Exercise**
Par. 15.4, p. 287 - starting the local build infrastructure with a local Git server, Docker registry and Jenkins server, using compose files in ch15/exercises/infrastructure. I used the linux containers

**Problem**
In Jenkins there should be a pre-configured job "diamol" - there isn't. 

**Docker version**
Docker version 20.10.2, build 2291f61

**Code version**
commit 19a8d04b1b4df0392ae6091c6ead8a680ad72368 (origin/master, origin/HEAD)
Author: Elton Stoneman <elton@sixeyed.com>
Date:   Fri Sep 25 09:10:55 2020 +0100

    Add ep. 20

**Additional context**
I tried: 1. switching back to default context; 2. removing images diamol/gogs, diamol/registry, diamol/jenkins so a new compose/run would pull the latest versions; 3. going back to chapter 11 and working through there from page 285 - did not work either (whereas previously it had)
![diamol_jenkins](https://user-images.githubusercontent.com/20972703/106930779-35885280-6716-11eb-8c6b-da46c699fdb6.png)

**Comment by sixeyed** [comment]
Hi @IraIAmOnIt - thanks for submitting the issue. Jenkins needed upgrading and I've pushed a new Docker image which fixes it.

You can pull the updated images with this command:

```
cd ch15/exercises/infrastructure

docker-compose pull
```

And then the exercises should work fine.
