### ISSUE TITLE
Ch11 Jenkins job "diamol" not pre-loaded   

### ISSUE THREAD

**Issue by jasonsalas** [sixeyed/diamol#27]
**Exercise**
From Page 189 under *Try It Now* - _"Browse to http:/ /localhost:8080. You’ll see the screen in figure 11.6—there’s already a job configured called diamol that is in the failed state."_ 

**Problem**
Jenkins installs and launches as expected, but there's no job already configured in the build, as the book states.

**Docker version**
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Code version**
commit 19a8d04b1b4df0392ae6091c6ead8a680ad72368 (HEAD -> master, origin/master, origin/HEAD, local/master)
Author: Elton Stoneman <elton@sixeyed.com>
Date:   Fri Sep 25 09:10:55 2020 +0100

    Add ep. 20

**Comment by sixeyed** [comment]
Thanks for submitting the issue Jason. The version of Jenkins needed updating, and I've pushed a new Docker image which fixes it. You can get the latest with this command:

```
cd ch11/exercises/infrastructure

docker-compose pull
```

And the exercises should run as expected.
