### ISSUE TITLE
Chapter 11.7 No Jenkins Pipeline diamol pre-loaded. Instruction of manual create job would be helpful - Solved

### ISSUE THREAD

**Issue by andsus** [sixeyed/diamol#28]
**Exercise**
Figure 11.7 of the book or page number 213 of the exercise.

**Problem**
No Jenkins Pipeline diamol pre-loaded. Instruction of manual create job would be helpful.

**Docker version**
Client:
 Debug Mode: false

Server:
 Containers: 27
  Running: 3
  Paused: 0
  Stopped: 24
 Images: 28
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-65-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.17GiB

**Code version**
Please run `git log -n 1` and paste the output.
Author: Elton Stoneman <elton@sixeyed.com>
Date:   Fri Sep 25 09:10:55 2020 +0100

    Add ep. 20

**Additional context**

**Comment by andsus** [comment]
Within Jenkins, Manage Jenkins > Plugin Manager > Scroll down and find Jenkins update button.
Click the restart Jenkins after install.
The job is visible after restart.

**Comment by sixeyed** [comment]
Thanks Andre for sending in the issue and providing your own fix :)

I've updated the Jenkins image now, if you pull the latest you should be fine:

```
cd ch11/exercises/infrastructure

docker-compose pull
```

**Comment by wbuelow-0425** [comment]
I am still having this issue after pulling the latest.
